### PR TITLE
Imgui tools

### PR DESCRIPTION
**Pull request by kortemik**
On behalf of @DanielGibson imgui tools pull request

### CODE REVIEW

**Comment by kortemik** [comment]
MinGW build fails on travis, this should be fixed.

Also we need to make imgui optional so some build system tuning is needed

**Comment by kortemik** [comment]
#91 is rebased and builds fine

**Comment by BielBdeLuna** [comment]
what is imGui?

**Comment by kortemik** [comment]
imGui is simple c++ gui, it's used it for tools rather than cegui at the moment

**Comment by BielBdeLuna** [comment]
ah ok, now I see it, pretty interesting, those days i was looking at how to tackle the damn MFC in doom3 tools, indeed imGUI seems to be a perfect fit

**Pull request closed without merging**
