### PR TITLE
macOS fixes

### PR DESCRIPTION
**Pull request by damiel**
Tested these fixes on my local machine, a MacBook Pro 13' from 2017. Currently OTE will only build on macOS when using sdl2. See my comment in neo/sys/posix/posix_main.cpp.

### CODE REVIEW

**Comment by damiel** [comment]
Now that i use mac as my main machine i started looking for mac related issues to fix, two things i already noted are problems with Breakpad and CEGUI, i think Breakpad is just missing integration but CEGUI seems to have a build dependency problem regarding the installed boost version. It requires an old boost version which is not so easily available as like for example simply installing boost via Homebrew.

**Comment by damiel** [comment]
Okay, the check succeded because of the travis settings being: 
allow_failures:- os: osx

I've just seen another, older pullrequest that actually already adresses the build errors on macOS so i did a bit of duplicated work here...

**Comment by damiel** [comment]
I will have to do some more adjustments to this until its good enough to merge. Working on it atm.

**Comment by kortemik** [comment]
I wonder what is the relationship to #90 as it has some stuff needed as well?

**Comment by damiel** [comment]
Well i plan on superseding #90 with my own pull request, i started incorporating changes from #90 that make sense like the travis integration. Once my pull request gets merged we can close #90.

**Comment by damiel** [comment]
Well f*ck, i found the issue, the build script get excluded by git because of a entry in .gitignores, trying to find a good compromiss here x) (Also i am stupid that i didnt saw that earlier :D)

**Comment by damiel** [comment]
Okay, OTE is now fully buildable on macOS/travis, thing to note is that the packaging using cpack seems to be broken for macOS at the moment, i will take care of that in a seperate pull request. I will clean up this pull request and proceed to merge it.

**Comment by BielBdeLuna** [comment]
congratulations! :)

**Comment by kortemik** [comment]
thank you damiel for finishing it!

**Pull request merged**
