### PR TITLE
Ironsight

### PR DESCRIPTION
**Pull request by BielBdeLuna**
additions for an iron sight button in the weapons

### CODE REVIEW

**Comment by kortemik** [comment]
Which script are we talking about? The weapon one? We have our own branch called assets and it contains gplv3 scripts for standalone functionality so .. no problem here :)

**Comment by BielBdeLuna** [comment]
what about a CC license?

**Comment by BielBdeLuna** [comment]
most of the script in the assets branch is distributed unlicensed which is wrong, your work could be stolen and re-licensed without you knowing it, and then you could be sued for "stole the works of others" even if you created your work from scratch and the "works of others" is a copy of yours re-licensed.

anyway, I do want to push for a GPL license in my assets. GPL doesn't prevent anyone to make money from my assets, specially if those are base assets, they can do their sub-classes as closed as they want. Also, if they want it, they can ask for permission in order to change my license to a closed one. if they don't have a problem asking I have no problem granting that.

**Comment by kortemik** [comment]
I would like us to use CC license with BY (Attribution only) in assets.. GPL assets are a bit hard for some to cope with, like in scripts even if one inherits from a file then s/he has to use GPL too.. LGPL would be copeable but then again, how would LGPL behave if one builds a container containing both our assets and their own? Would that go under distribute medium as the container is extractable?

**Comment by DanielGibson** [comment]
> most of the script in the assets branch is distributed unlicensed which is wrong, at east give it Daniel's license your work could be stolen and re-licensed without you knowing it, and then you could be sued for "stole the works of others" even if you created your work from scratch and the "works of others" is a copy of yours re-licensed.

I really doubt that this is a plausible scenario.
I put my copyright in those files and via git history it's public and obvious when I created them, so no one can really sue me after copying them and putting their own (C) on them.  
At least not any more than they could with a GPL license (they could just copy my code, remove my copyright and the license header and claim they invented it in that case, too)

Just to clarify: This is not about the C++ code, but only about the stuff in base/ (textures, materials, definitions, scripts, ...)

These are *base* assets. nothing great, just the minimum to get a doom3-engine based game running. I'd like to make that as painless as possible for potential users, without having to worry about the license of single scripts they're reusing/adapting.  

> Also, if they want it, they can ask for permission in order to change my license to a closed one.

This is not viable for a project like OpenTech. In the end we would possibly have dozens of contributers that contributed some materials, scripts, ... that someone creating a commercial game would have to ask.  
Experience shows that this is very difficult, especially after a few years, when some contributers disappear from the scene (and sometimes, sadly, from the world).  
Thus I'd like to use a very permissive license right from the start.

LGPL is not an option really, it's for libraries you link against, not for assets. No idea how one would even apply the LGPL to scripts and such.

**Comment by BielBdeLuna** [comment]
you might find it more troublesome when you start developing the AI FSM, the scripting then looks like c++ codeand you want to set it on a WTF licence? that can be a lot of work to give without any due credit.

and what is the problem of distributing the source code and assets along the original product? it's not like you're forced to distribute it for free! once you pay for the product you have the product and the assets (at least those that are GPL, the others can be as closed as you want)

for GPL water code in the darkmod Motorsep an I went on to find the original authors or someone in the Darkmod team in order to have their permission, the water was GPL but it wasn't stated in the files as the dark mod started with SDK files which weren't GPL at that time. 
Also with GPL since you don't have to create the thing at least having the hassle of searching the author to get permission doesn't seem that big a penalty isn't it?

if the author is dead, GPL doesn't give powers to any heir on the distributed code, so why is any worse?

@kortemik: but you don't inherit the license of a file if it's GPL, you inherit it's data. the right hand can be GPL while the left hand is closed to death, as long as you don't distribute their code outside the boundaries of their license, you are allright, and can use both codes alongside.

C'mon guys, GPL wasn't meant to stop anyone from developing anything but to help others refine and re-create the GPL licensed stuff.

**Comment by DanielGibson** [comment]
The goal of OpenTech is not to create a game, but an engine/SDK.
So I don't think we'll provide very complicated AI scripts, maybe some basics ones that show how to use the interfaces (same for weapons).

> Also with GPL since you don't have to create the thing at least having the hassle of searching the author to get permission doesn't seem that big a penalty isn't it?

If it's dozens of small things it is.

> if the author is dead, GPL doesn't give powers to any heir on the distributed code, so why is any worse?

not sure I understand that sentence, but if the author is dead it will be very hard to get a permission to re-license things (as you suggested with "Also, if they want it, they can ask for permission in order to change my license to a closed one.")

I think relicensing later is bad/hard, so I'd like to avoid the need for relicensing by choosing a very liberal license for this  stuff in the first place.

come on, we're only talking about very simple scripts here, I'm not even sure they'd meet the "threshold of originality".

If in the future we should decide to make a proper "demo game" with high-quality levels, enemies (+AI), weapons, textures, ... that stuff can certainly be put under a more restrictive license (and should probably be in a different repository anyway)

**Comment by BielBdeLuna** [comment]
fine, go ahead change my license if you want, or we will never end up this conversation.

**Comment by DanielGibson** [comment]
If you don't like the WTFPL, we could also agree on using CC0 or maybe the zlib-license which seem a bit more "official" :)

**Comment by BielBdeLuna** [comment]
no, go ahead with the WTFPL at least let all the assets have the same lic. 

besides this, shouldn't we add this lic. to all the script files, most of them doesn't have any lic. so at least have something.

**Comment by BielBdeLuna** [comment]
we'll discuss this again when I finish up my "GPL" AI I'm currently working on:
http://idtechforums.fuzzylogicinc.com/index.php?topic=133.0

**Comment by BielBdeLuna** [comment]
I still think giving up all our valuable time and energy for free with any need for even a credit, is very disrespectful for our-selves

**Comment by DanielGibson** [comment]
yeah, I think we should add it to all text files that allow comments.
that's not possible with images, of course, but we could just mention in the COPYING.TXT that they're also under WTFPL.

Regarding your GPL AI: If you create nontrivial AI scripts then putting them under a more restrictive license is fine with me.  
I just want the simple stuff to be very free :)

> I still think giving up all our valuable time and energy for free with any need for even a credit, is very disrespectful for our-selves

I think we spend most of the time with C++ Code, that is under GPLv3 and thus will give us credit. I consider these basic scripts just simple glue between the C++ engine and game-specific assets.

**Comment by DanielGibson** [comment]
And we should also put contributors in a contributors list, so there is some credit besides the WTFPL-line in the scripts.

Oh btw, does this mean you're also OK with changing the license of the Portal-Sky scripts/defs/materials/textures under WTFPL?


And thanks *a lot* for changing your mind :-)

**Comment by BielBdeLuna** [comment]
yes, change the portal sky. at least the lic is consistent, the textures tough, let's not put them in CC0 as they are dev textures, they are non-esential for a game developer to distribute, so they can use the GPLv3 version and not distribute them outside it, and since they are so simple they can always do their own... hah! gotcha! :P

**Comment by DanielGibson** [comment]
they'd still have to make sure not to redistribute them..  
I actually recreated most doom3 editor textures under WTFPL, just to eliminate this problem (the only ones I didn't recreate were already released to the public domain).

Let's not create license "traps" by mixing WTFPL assets with ones under a much more restrictive license. For nontrivial stuff like your GPL AI we might create a base/GPL/ directory, just to make this very obvious for users.

**Comment by BielBdeLuna** [comment]
the problem with base/GPL/ dir is that this means essentially create two families of code if you end up using the more complex of the two why bother with the other?

I would think that using a base of WTFPL works (like all the base scripts and the main scripts should suffice to make the engine usable

but then on the guns scripts and the monster AI and the utils scripts you could have GPL stuff

**Comment by BielBdeLuna** [comment]
maybe devising a way to compartmentalise the content could be an answer, like they did with OpenAerna were some stuff was put in paks that could be redistributed independently than the rest of the project, or how different missions in the Darkmod add to the base games the independently needed content.

**Comment by DanielGibson** [comment]
> I would think that using a base of WTFPL works (like all the base scripts and the main scripts should suffice to make the engine usable
> but then on the guns scripts and the monster AI and the utils scripts you could have GPL stuff

this is essentially the idea, except that *maybe* having very simple weapon/monster examples under WTFPL would be nice too, so projects that don't want to use the GPL scripts at least have a starting point.  
in practice this could mean that we start some very simple scripts that somehow make the weapon/monster do *something* and release those under WTFPL, while later iterations of those scripts with more complex logic are under GPL

**Comment by BielBdeLuna** [comment]
this is downright evil! :) I updated the lic to WTFPL2, do I merge?

**Comment by DanielGibson** [comment]
uhh one small thing I just noticed: you indented with spaces, but we usually use tabs for that, so with tabsize != 4 it looks strange.

but maybe we should just run this astyle script again sometime...

**Comment by BielBdeLuna** [comment]
can you run it, I edited it form github itself, cause I'm coding something else in my repo in my hdd.

**Comment by DanielGibson** [comment]
I'll just merge it for now, will run astyle later

**Pull request merged**
