### PR TITLE
Renderfixes:

### PR DESCRIPTION
**Pull request by damiel**
This commit ports a bunch of render fixes from rbdoom3bfg to ote,
including a fix for issue #83.

### CODE REVIEW

**Comment by BielBdeLuna** [comment]
great!

**Comment by Yetta1** [comment]
Thank you damiel.

**Comment by DanielGibson** [comment]
would it be possible to cherry pick the corresponding commits from rbd3bfg? that would probably make it easier to merge other changes later.. or are these fixes parts of bigger commits that we  (mostly) don't want/need?

**Comment by damiel** [comment]
It depends a bit, some of the commits where mixed up with stuff that is unnecessary for us, other commits have include parts that got later reverted or add some noise (like outcommented code that isnt even is use) and some files had mismatching lines making the cherrypick fail. In this case it was just easier to port all the smaller changes in one go by being handpicked.

But i think later commits from rbd3bfg like SSAO and SMAA can be cherrypicked. (and i plan on doing so for my next pr's).

**Comment by BielBdeLuna** [comment]
Without those fixes, the engine can only be played with OpenGL Compat with Mesa drivers, and so you're stuck with OpenGL 3.0 on all hardware, because the GLSL changed sine that version of OpenGL that's the reason the changes in the CG files

**Pull request merged**
