### PR TITLE
Cegui switcher

### PR DESCRIPTION
**Pull request by kortemik**
base for implementing menus in cegui

### CODE REVIEW

**Comment by BielBdeLuna** [comment]
great!

**Comment by DanielGibson** [comment]
I think it's fine :-)

:+1:

**Comment by BielBdeLuna** [comment]
I'm sorry to post this but i don't know how to contact you guys directly I'm making a blender-->idTechX map exporter, I request it to be part of the Open Tech initiative:

http://idtechforums.fuzzylogicinc.com/index.php?topic=203.0

https://github.com/BielBdeLuna/Blender_IDtech4_GPL_map

what do you think?
is there a messaging option in Github?

**Comment by kortemik** [comment]
Hey! Awesome work you put there, we want it definitely as part of OTE, we have the rest of the tools here https://github.com/OpenTechEngine/ModelingTools but i think we should have own repo for it to be able to sync with you more frequently. What do you think? I wish DG would have some comments on this too :)

**Comment by DanielGibson** [comment]
Sounds interesting.  
Once it works a bit more (at least textures should kinda work IMHO) we could give you a repo under github.com/OpenTechEngine/

Does brush based modeling/map creation with blender work well?

**Comment by BielBdeLuna** [comment]
idk I will have to find out

**Pull request merged**
